import org.gradle.api.attributes.java.TargetJvmVersion

plugins {
    id 'java'
    id 'io.github.goooler.shadow' version '8.1.5'
}

def hasProject = { String path -> rootProject.findProject(path) != null }

allprojects {
    apply plugin: 'java'

    group = 'nl.knokko.customitems'

    repositories {
        mavenCentral()

        maven { url = 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url = 'https://maven.enginehub.org/repo/' }
        maven { url = 'https://repo.crazycrew.us/releases' }
        maven { url = 'https://repo.citizensnpcs.co' }
        maven { url = 'https://jitpack.io' }
        maven { url = 'https://maven.elmakers.com/repository/' }
        maven { url = 'https://repo.codemc.io/repository/maven-public/' }
        maven { url = 'https://repo.opencollab.dev/main/' }

        mavenLocal()
        maven { url = 'https://repo.skriptlang.org/releases' }
    }

    java {
        toolchain {
            languageVersion = JavaLanguageVersion.of(21)
        }
        sourceCompatibility = JavaVersion.VERSION_1_8
        targetCompatibility = JavaVersion.VERSION_1_8
    }

    tasks.withType(JavaCompile).configureEach {
        options.release.set(8)
    }

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter-api:5.10.0'
        testRuntimeOnly 'org.junit.jupiter:junit-jupiter-engine:5.10.0'
    }

    test {
        useJUnitPlatform()
    }
}

project(':shared-code') {
    dependencies {
        implementation project(':bit-helper')
        implementation 'com.github.cliftonlabs:json-simple:4.0.1'
    }
}

project(':plug-in') {
    apply plugin: 'io.github.goooler.shadow'
    dependencies {
        implementation project(':shared-code')
        implementation project(':kci-nms')
        implementation project(':custom-recipes')
        implementation 'com.github.cliftonlabs:json-simple:4.0.1'
        if (hasProject(':kci-nms12')) runtimeOnly project(':kci-nms12')
        if (hasProject(':kci-nms13plus')) runtimeOnly project(':kci-nms13plus')
        if (hasProject(':kci-nms13')) runtimeOnly project(':kci-nms13')
        if (hasProject(':kci-nms14')) runtimeOnly project(':kci-nms14')
        if (hasProject(':kci-nms15')) runtimeOnly project(':kci-nms15')
        if (hasProject(':kci-nms16plus')) runtimeOnly project(':kci-nms16plus')
        if (hasProject(':kci-nms16')) runtimeOnly project(':kci-nms16')
        if (hasProject(':kci-nms17')) runtimeOnly project(':kci-nms17')
        if (hasProject(':kci-nms18plus')) runtimeOnly project(':kci-nms18plus')
        if (hasProject(':kci-nms18')) runtimeOnly project(':kci-nms18')
        if (hasProject(':kci-nms19')) runtimeOnly project(':kci-nms19')
        if (hasProject(':kci-nms20')) runtimeOnly project(':kci-nms20')
        if (hasProject(':kci-nms21plus')) runtimeOnly project(':kci-nms21plus')
        if (hasProject(':kci-nms21')) runtimeOnly project(':kci-nms21')
        if (hasProject(':kci-nms21r1')) runtimeOnly project(':kci-nms21r1')
        if (hasProject(':ce-event-handler')) runtimeOnly project(':ce-event-handler')
        compileOnly project(':bit-helper')
        compileOnly 'org.bukkit:bukkit:1.12.2-R0.1-SNAPSHOT'
        compileOnly 'com.sk89q.worldguard:worldguard-bukkit:7.0.0'
        compileOnly 'ru.endlesscode.mimic:mimic-bukkit-api:0.7.1'
        compileOnly 'com.github.jojodmo:ItemBridge:master-SNAPSHOT'
        compileOnly 'com.elmakers.mine.bukkit:MagicAPI:9.3'
        compileOnly 'org.geysermc.geyser:api:2.2.0-SNAPSHOT'
        implementation 'de.tr7zw:item-nbt-api:2.15.3-SNAPSHOT'

        testImplementation project(':bit-helper')
        testImplementation 'org.bukkit:bukkit:1.12.2-R0.1-SNAPSHOT'
    }
    configurations.runtimeClasspath {
        attributes.attribute(TargetJvmVersion.TARGET_JVM_VERSION_ATTRIBUTE, 21)
    }
    shadowJar {
        relocate('de.tr7zw.changeme.nbtapi', 'nl.knokko.customitems.plugin.shadow.nbtapi')
        relocate('kr.toxicity.libraries.datacomponent', 'nl.knokko.customitems.plugin.shadow.datacomponent')
    }
}

project(':custom-recipes') {
    dependencies {
        compileOnly 'org.spigotmc:spigot-api:1.16.5-R0.1-SNAPSHOT'
    }
}

if (hasProject(':test-custom-recipes')) {
    project(':test-custom-recipes') {
        dependencies {
            testImplementation project(':custom-recipes')
            testImplementation 'com.github.seeseemelk:MockBukkit-v1.20:3.9.0'
        }
    }
}

project(':editor') {
    apply plugin: 'io.github.goooler.shadow'
    dependencies {
        implementation project(':shared-code')
        implementation project(':bit-helper')
        implementation project(':gui')
        implementation 'com.github.cliftonlabs:json-simple:4.0.1'

        implementation platform("org.lwjgl:lwjgl-bom:3.3.1")
        implementation "org.lwjgl:lwjgl"
        implementation "org.lwjgl:lwjgl-nfd"

        runtimeOnly "org.lwjgl:lwjgl::natives-linux"
        runtimeOnly "org.lwjgl:lwjgl-nfd::natives-linux"
        runtimeOnly "org.lwjgl:lwjgl::natives-linux-arm32"
        runtimeOnly "org.lwjgl:lwjgl-nfd::natives-linux-arm32"
        runtimeOnly "org.lwjgl:lwjgl::natives-linux-arm64"
        runtimeOnly "org.lwjgl:lwjgl-nfd::natives-linux-arm64"

        runtimeOnly "org.lwjgl:lwjgl::natives-macos"
        runtimeOnly "org.lwjgl:lwjgl-nfd::natives-macos"
        runtimeOnly "org.lwjgl:lwjgl::natives-macos-arm64"
        runtimeOnly "org.lwjgl:lwjgl-nfd::natives-macos-arm64"

        runtimeOnly "org.lwjgl:lwjgl::natives-windows"
        runtimeOnly "org.lwjgl:lwjgl-nfd::natives-windows"
        runtimeOnly "org.lwjgl:lwjgl::natives-windows-x86"
        runtimeOnly "org.lwjgl:lwjgl-nfd::natives-windows-x86"
        runtimeOnly "org.lwjgl:lwjgl::natives-windows-arm64"
        runtimeOnly "org.lwjgl:lwjgl-nfd::natives-windows-arm64"
    }
    shadowJar {
        manifest {
            attributes ('Main-Class': 'nl.knokko.customitems.editor.Editor')
        }
    }
}

project(':yaml-resourcepack-cli') {
    apply plugin: 'io.github.goooler.shadow'
    dependencies {
        implementation project(':plug-in')
        implementation 'org.bukkit:bukkit:1.12.2-R0.1-SNAPSHOT'
    }
    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    tasks.withType(JavaCompile).configureEach {
        options.release.set(21)
    }
    shadowJar {
        manifest {
            attributes('Main-Class': 'nl.knokko.customitems.plugin.yaml.YamlResourcepackCli')
        }
    }
}

project(':yaml-resourcepack-source-cli') {
    apply plugin: 'io.github.goooler.shadow'
    dependencies {
        implementation project(':plug-in')
        implementation project(':shared-code')
        implementation 'org.bukkit:bukkit:1.12.2-R0.1-SNAPSHOT'
    }
    java {
        sourceCompatibility = JavaVersion.VERSION_21
        targetCompatibility = JavaVersion.VERSION_21
    }
    tasks.withType(JavaCompile).configureEach {
        options.release.set(21)
    }
    shadowJar {
        manifest {
            attributes('Main-Class': 'nl.knokko.customitems.plugin.yaml.YamlSourceResourcepackCli')
        }
    }
}

if (hasProject(':ce-event-handler')) {
    project(':ce-event-handler') {
        dependencies {
            compileOnly project(':plug-in')
            compileOnly project(':shared-code')
            compileOnly 'com.badbones69.crazyenchantments:crazyenchantments-paper-api:2.1.2'
            compileOnly 'org.bukkit:bukkit:1.12.2-R0.1-SNAPSHOT'
            compileOnly 'com.github.SkriptLang:Skript:2.12.1'
            compileOnly 'com.denizenscript:denizen:1.3.1-SNAPSHOT'
        }
    }
}

project(':kci-nms') {
    dependencies {
        compileOnly project(':shared-code')
        compileOnly 'org.bukkit:bukkit:1.12.2-R0.1-SNAPSHOT'
    }
}

if (hasProject(':kci-nms12')) {
    project(':kci-nms12') {
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly 'org.bukkit:craftbukkit:1.12.2-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms13plus')) {
    project(':kci-nms13plus') {
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly 'org.bukkit:bukkit:1.13.2-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms13')) {
    project(':kci-nms13') {
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly 'org.bukkit:craftbukkit:1.13.2-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms14')) {
    project(':kci-nms14') {
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly 'org.bukkit:craftbukkit:1.14.4-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms15')) {
    project(':kci-nms15') {
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly 'org.spigotmc:spigot:1.15.2-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms16plus')) {
    project(':kci-nms16plus') {
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly 'org.spigotmc:spigot:1.16.5-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms16')) {
    project(':kci-nms16') {
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly project(':kci-nms16plus')
            compileOnly 'org.spigotmc:spigot:1.16.5-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms17')) {
    project(':kci-nms17') {
        java {
            sourceCompatibility = JavaVersion.VERSION_16
            targetCompatibility = JavaVersion.VERSION_16
        }
        tasks.withType(JavaCompile).configureEach {
            options.release.set(16)
        }
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly project(':kci-nms16plus')
            compileOnly 'org.spigotmc:spigot:1.17.1-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms18plus')) {
    project(':kci-nms18plus') {
        java {
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        }
        tasks.withType(JavaCompile).configureEach {
            options.release.set(17)
        }
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly project(':kci-nms16plus')
            compileOnly 'org.spigotmc:spigot:1.18.2-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms18')) {
    project(':kci-nms18') {
        java {
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        }
        tasks.withType(JavaCompile).configureEach {
            options.release.set(17)
        }
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly project(':kci-nms16plus')
            compileOnly project(':kci-nms18plus')
            compileOnly 'org.spigotmc:spigot:1.18.2-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms19')) {
    project(':kci-nms19') {
        java {
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        }
        tasks.withType(JavaCompile).configureEach {
            options.release.set(17)
        }
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly project(':kci-nms16plus')
            compileOnly project(':kci-nms18plus')
            compileOnly 'org.spigotmc:spigot:1.19.4-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms20')) {
    project(':kci-nms20') {
        java {
            sourceCompatibility = JavaVersion.VERSION_17
            targetCompatibility = JavaVersion.VERSION_17
        }
        tasks.withType(JavaCompile).configureEach {
            options.release.set(17)
        }
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly project(':kci-nms16plus')
            compileOnly project(':kci-nms18plus')
            compileOnly 'org.spigotmc:spigot:1.20.6-R0.1-SNAPSHOT'
            compileOnly 'net.kyori:adventure-api:4.17.0'
            implementation 'com.github.knokko:DataComponentAPI:b8f529f78e86b357b5d24ccad95408c9772ef4aa'
        }
    }
}

if (hasProject(':kci-nms21plus')) {
    project(':kci-nms21plus') {
        java {
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }
        tasks.withType(JavaCompile).configureEach {
            options.release.set(21)
        }
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly project(':kci-nms16plus')
            compileOnly project(':kci-nms18plus')
            compileOnly "io.papermc.paper:paper-api:1.21.11-R0.1-SNAPSHOT"
        }
    }
}

if (hasProject(':kci-nms21')) {
    project(':kci-nms21') {
        java {
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }
        tasks.withType(JavaCompile).configureEach {
            options.release.set(21)
        }
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly project(':kci-nms16plus')
            compileOnly project(':kci-nms18plus')
            compileOnly project(':kci-nms21plus')
            compileOnly 'org.spigotmc:spigot:1.21.11-R0.1-SNAPSHOT'
        }
    }
}

if (hasProject(':kci-nms21r1')) {
    project(':kci-nms21r1') {
        java {
            sourceCompatibility = JavaVersion.VERSION_21
            targetCompatibility = JavaVersion.VERSION_21
        }
        tasks.withType(JavaCompile).configureEach {
            options.release.set(21)
        }
        dependencies {
            compileOnly project(':kci-nms')
            compileOnly project(':kci-nms13plus')
            compileOnly project(':kci-nms16plus')
            compileOnly project(':kci-nms18plus')
            compileOnly project(':kci-nms21plus')
            compileOnly 'org.spigotmc:spigot:1.21.1-R0.1-SNAPSHOT'
        }
    }
}
